SpiralWorks.Web/Models/TransactionViewModel.cs
using System.Collections.Generic;

namespace SpiralWorks.Web.Models
{
    public class TransactionViewModel
    {
        public int AccountId { get; set; }
        public IEnumerable<TransactionItemViewModel> TransactionList { get; set; }

    }
}

SpiralWorks.Web/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SpiralWorks.Interfaces;
using SpiralWorks.Web.Helpers;
using SpiralWorks.Web.Models;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc.Rendering;
using SpiralWorks.Model;

namespace SpiralWorks.Web.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        ITransactionService _transactionService;
        IAccountService _accountService;
        ISession _session;
        User _currentUser;
        public TransactionController(ITransactionService transactionService, IAccountService accountService, IHttpContextAccessor httpContextAccessor)
        {
            _transactionService = transactionService;
            _accountService = accountService;
            _session = httpContextAccessor.HttpContext.Session;
            _currentUser = _session.Get<User>("CurrentUser");
        }

        public IActionResult Index(int? id)
        {

            var list = new List<TransactionItemViewModel>();
            int.TryParse(id.ToString(), out int accountId);
            var items = _transactionService.GetTransactions(accountId);
            items.ForEach(x =>
            {
                var entity = new TransactionItemViewModel();
                x.CopyTo(entity);
                list.Add(entity);
            });

            var model = new TransactionViewModel()
            {
                AccountId = accountId,
                TransactionList = list
            };

            return View(model);
        }
        [HttpGet]
        public IActionResult List(int accountId)
        {
            var list = new List<TransactionItemViewModel>();

            if (accountId > 0)
            {
                var items = _transactionService.GetTransactions(accountId);

                items.ForEach(x =>
                {
                    var entity = new TransactionItemViewModel();
                    x.CopyTo(entity);
                    list.Add(entity);
                });
            }
            return PartialView("TransactionList", list);
        }
        [HttpGet]
        public ActionResult Create(int? id)
        {

            int.TryParse(id.ToString(), out int accountId);
            var model = new TransactionItemViewModel()
            {
                TransactionType = "DEP",
                AccountId = accountId,
                DateCreated = DateTime.Now
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(TransactionItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                TimeSpan ts = new TimeSpan();


                var account = _accountService.GetAccount(model.AccountId);

                var transaction = new Transaction()
                {
                    TransactionType = model.TransactionType,
                    AccountId = model.AccountId,
                    DateCreated = model.DateCreated,
                    Balance = account?.Balance ?? 0,
                    RowVersion = ts.ToByteArray()
                };
                var recipient = new Transaction();

                switch (model.TransactionType)
                {
                    case "DEP":
                        transaction.Debit = model.Amount;
                        transaction.Balance = transaction.Balance + transaction.Debit;
                        account.Balance = transaction.Balance;
                        break;

                    case "WIT":
                        transaction.Credit = model.Amount;
                        transaction.Balance = transaction.Balance - transaction.Credit;
                        account.Balance = transaction.Balance;
                        break;

                    case "TOA":
                    case "TSA":
                        transaction.Credit = model.Amount;
                        transaction.ToAccountId = model.ToAccountId;

                        var recipientAccount = _accountService.GetAccount(model.ToAccountId);

                        recipient.AccountId = transaction.ToAccountId;
                        recipient.TransactionType = "TRF";
                        recipient.Debit = model.Amount;
                        recipient.ToAccountId = model.AccountId;
                        recipient.DateCreated = DateTime.Now;
                        recipient.Balance = recipientAccount.Balance + model.Amount;

                        _accountService.UpdateAccount(recipientAccount);

                        _transactionService.CreateTransaction(recipient);
                        break;

                    default:
                        break;
                }

                _transactionService.CreateTransaction(transaction);
                _accountService.UpdateAccount(account);



                return RedirectToAction("Index", new RouteValueDictionary(new { id = model.AccountId }));
            }
            return View(model);
        }

        public IActionResult AccountList(string transactionType)
        {
            SelectList selectList = null;
            if (transactionType == "TOA")
            {
                selectList = SelectListHelper.AccountList(_accountService, _currentUser.UserId);
            }
            else
            {
                selectList = SelectListHelper.OtherAccountList(_accountService, _currentUser.UserId);
            }
            return new JsonResult(selectList);
        }
    }
}

SpiralWorks.Web/Views/Transaction/Create.cshtml
@model SpiralWorks.Web.Models.TransactionItemViewModel
@using SpiralWorks.Web.Helpers;
@using SpiralWorks.Interfaces;
@inject IAccountService service;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Create";
    var user = HttpContextAccessor.HttpContext.Session.Get<SpiralWorks.Model.User>("CurrentUser");
}
<br />
<div class="container">
    <div class="well">
        <div class="container">
            <div class="row">
                <h3>Create</h3>
                <h4>Bank Transaction</h4>
                <hr />
            </div>
            <div class="row">
                <form asp-action="Create" method="post">
                    <div class="row">
                        <div class="col-md-6">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label>Transaction Type</label>
                                <select id="TransactionType" asp-for="TransactionType" class="form-control" asp-items="@SelectListHelper.TransactionTypeList()" onchange="LoadAccounts()"></select>
                                <span asp-validation-for="TransactionType" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label>Bank Accounts</label>
                                <select id="AccountId" asp-for="AccountId" class="form-control" asp-items="@SelectListHelper.AccountList(service, user.UserId)" onchange=""></select>
                                <span asp-validation-for="AccountId" class="text-danger"></span>
                            </div>
                            <div id="ToAccountIdGroup" class="form-group" style="display:none;">
                                <label>Transfer To </label>
                                <select id="ToAccountId" asp-for="ToAccountId" class="form-control" onchange=""></select>
                                <span asp-validation-for="ToAccountId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Amount" class="control-label"></label>
                                <input asp-for="Amount" class="form-control" />
                                <span asp-validation-for="Amount" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="DateCreated" class="control-label"></label>
                                <div class='input-group date' id='DateCreated'>
                                    <input asp-for="DateCreated" class="form-control" type='date' />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                                <span asp-validation-for="DateCreated" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-12 text-left">
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary" />
                                <input type="hidden" asp-for="RowVersion" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-left">
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function LoadAccounts() {
        var tranType = $("#TransactionType").val();

        if (tranType === "TOA" || tranType === "TSA") {
            $("#ToAccountIdGroup").show();
            $.ajax({
                url: '@Url.Action("AccountList", "Transaction")',
                data: {
                    transactionType: tranType
                },
                cache: false,
                type: 'POST',
                success: function (data) {
                    $('#ToAccountId option').remove();
                    var i = 0;
                    for (x in data) {
                        i++;
                        $("#ToAccountId").append("<option value='" + data[i].value + "'>" + data[i].text + "</option>")
                    }
                }
            });
        } else {
            $("#ToAccountIdGroup").hide();

        }
    };
</script>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}


SpiralWorks.Web/Views/Transaction/Index.cshtml
@model TransactionViewModel
@using SpiralWorks.Interfaces;
@using SpiralWorks.Web.Helpers;
@inject IAccountService service;
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor;

@{
    ViewData["Title"] = "Index";
    var user = HttpContextAccessor.HttpContext.Session.Get<SpiralWorks.Model.User>("CurrentUser");
}

<br />
<form name="form1" asp-controller="Transaction" asp-action="Index">
    <div class="container">
        <div class="well">
            <div class="row">
                <div class="col-md-12">
                    <h3>Bank Transactions</h3>
                    <p>
                        <a id="Create" class="btn btn-success btn-sm" asp-action="Create" asp-route-id="@Model.AccountId">Create New</a>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-offset-4">
                    <div class="form-group">
                        <label>Bank Accounts</label>
                        <select id="AccountId" asp-for="AccountId" class="form-control" asp-items="@SelectListHelper.AccountList(service, user.UserId)" onchange="DoPostBack();"></select>
                        <span asp-validation-for="AccountId" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" id="transactList">
                    @{
                        await Html.RenderPartialAsync("TransactionList", Model.TransactionList);
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-left">
                    <a asp-controller="Account" asp-action="Index">Back to Accounts</a>
                </div>
            </div>



        </div>
    </div>
</form>
<script type="text/javascript">


            function DoPostBack() {
                var id = $('#AccountId').val();
                $("#Create").attr("href", "/Transaction/Create/" + id);
                 $.ajax({
                     url: '@Url.Action("List", "Transaction")',
                     data: {
                         accountId: id
                     },
                    cache: false,
                    type: 'get'
                }).done(function (response) {
                    $('#transactList').html(response);

                });
            }


</script>

SpiralWorks.Web/Views/Transaction/TransactionList.cshtml
@model IEnumerable<TransactionItemViewModel>
@using SpiralWorks.Interfaces;
@using SpiralWorks.Web.Helpers;
@inject IAccountService service;
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TransactionId)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.AccountNumber)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.TransactionType)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Debit)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Credit)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Balance)

            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.RowVersion)

            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var description = (item.TransactionType.Equals("DEP")) ? "(Deposit)" : (item.TransactionType.Equals("WIT")) ? "(Withdrawal)" : (item.TransactionType.Equals("TRF")) ? $"(Transferred from {item.ToAccountId.GetAccountNumber(service)})" : $"(Transferred to {item.ToAccountId.GetAccountNumber(service)})";
            <tr>
                <th scope="row">
                    @item.TransactionId
                </th>
                <td>
                    @item.AccountId.GetAccountNumber(service)
                </td>
                <td>
                    @item.TransactionType  @description
                </td>
                <td>
                    @item.Debit.EmptyOrDefault()
                </td>
                <td>
                    @item.Credit.EmptyOrDefault()
                </td>
                <td>
                    @item.Balance
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RowVersion)
                </td>
                <td>
                    @item.DateCreated.ToShortDateString()
                </td>
            </tr>
        }
    </tbody>
</table>